[package]
org = "adeep"
name = "Backend"
version = "0.1.0"
distribution = "2201.12.7"

[build-options]
observabilityIncluded = true


[[dependency]]
org = "ballerina"
name = "http"
version = "2.12.0"

[[dependency]]
org = "ballerinax"
name = "mongodb"
version = "5.2.1"